import { GeneratedTest, Question, TestConfig } from './types';

export const MATH_10_QUESTIONS: Question[] = [
  // PHẦN I: 12 CÂU TRẮC NGHIỆM LỚP 10
  {
    id: 'q10_1',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Mệnh đề toán học',
    content: 'Phủ định của mệnh đề $P$: "$\\forall x \\in \\mathbb{R}, x^2 + 1 > 0$" là mệnh đề:',
    options: [
      { key: 'A', text: '"$\\exists x \\in \\mathbb{R}, x^2 + 1 \\le 0$"' },
      { key: 'B', text: '"$\\exists x \\in \\mathbb{R}, x^2 + 1 < 0$"' },
      { key: 'C', text: '"$\\forall x \\in \\mathbb{R}, x^2 + 1 \\le 0$"' },
      { key: 'D', text: '"$\\exists x \\in \\mathbb{R}, x^2 + 1 > 0$"' },
    ],
    correctAnswer: 'A',
    solution: 'Phủ định của $\\forall$ là $\\exists$, phủ định của dấu $>$ là $\\le$.',
  },
  {
    id: 'q10_2',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Tập hợp',
    content: 'Cho hai tập hợp $A = [-2; 3]$ và $B = (1; 5)$. Giao của hai tập hợp $A \\cap B$ là:',
    options: [
      { key: 'A', text: '$(1; 3]$' },
      { key: 'B', text: '[-2; 5)' },
      { key: 'C', text: '[1; 3]' },
      { key: 'D', text: '(-2; 1]' },
    ],
    correctAnswer: 'A',
    solution: 'Phần tử chung của cả hai tập là $(1; 3]$.',
  },
  {
    id: 'q10_3',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Dấu tam thức bậc hai (Có Bảng xét dấu)',
    content: 'Cho tam thức bậc hai $f(x)$ có bảng xét dấu như sau:\n$$\\begin{array}{c|ccccccc} x & -\\infty & & -2 & & 3 & & +\\infty \\\\ \\hline f(x) & & + & 0 & - & 0 & + & \\end{array}$$\nTập nghiệm của bất phương trình $f(x) < 0$ là:',
    options: [
      { key: 'A', text: '$(-2; 3)$' },
      { key: 'B', text: '$(-\\infty; -2) \\cup (3; +\\infty)$' },
      { key: 'C', text: '$[-2; 3]$' },
      { key: 'D', text: '$(-\\infty; -2]$' },
    ],
    correctAnswer: 'A',
    solution: 'Dựa vào bảng xét dấu, $f(x) < 0$ khi $x \\in (-2; 3)$.',
  },
  {
    id: 'q10_4',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Hàm số bậc hai',
    content: 'Tọa độ đỉnh $I$ của parabol $y = x^2 - 4x + 3$ là:',
    options: [
      { key: 'A', text: '$I(2; -1)$' },
      { key: 'B', text: '$I(-2; 15)$' },
      { key: 'C', text: '$I(4; 3)$' },
      { key: 'D', text: '$I(2; 3)$' },
    ],
    correctAnswer: 'A',
    solution: '$x_I = -b/(2a) = 4/2 = 2 \\Rightarrow y_I = 2^2 - 4(2) + 3 = -1$.',
  },
  {
    id: 'q10_5',
    type: 'multiple_choice',
    level: 'ThongHieu',
    topicName: 'Hệ thức lượng trong tam giác',
    content: 'Cho tam giác $ABC$ có $AB = 3, AC = 4$ và góc $\\widehat{A} = 60^\\circ$. Độ dài cạnh $BC$ bằng:',
    options: [
      { key: 'A', text: '$\\sqrt{13}$' },
      { key: 'B', text: '$5$' },
      { key: 'C', text: '$\\sqrt{37}$' },
      { key: 'D', text: '$\\sqrt{7}$' },
    ],
    correctAnswer: 'A',
    solution: '$BC^2 = 3^2 + 4^2 - 2(3)(4)\\cos 60^\\circ = 9 + 16 - 12 = 13 \\Rightarrow BC = \\sqrt{13}$.',
  },
  {
    id: 'q10_6',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Tích vô hướng hai vectơ',
    content: 'Trong mặt phẳng tọa độ $Oxy$, cho $\\vec{u} = (2; -3)$ và $\\vec{v} = (4; 1)$. Tích vô hướng $\\vec{u} \\cdot \\vec{v}$ bằng:',
    options: [
      { key: 'A', text: '$5$' },
      { key: 'B', text: '$11$' },
      { key: 'C', text: '$8$' },
      { key: 'D', text: '$-5$' },
    ],
    correctAnswer: 'A',
    solution: '$\\vec{u} \\cdot \\vec{v} = 2(4) + (-3)(1) = 8 - 3 = 5$.',
  },
  {
    id: 'q10_7',
    type: 'multiple_choice',
    level: 'ThongHieu',
    topicName: 'Phương trình đường thẳng Oxy',
    content: 'Đường thẳng đi qua $M(1; 2)$ và có vectơ pháp tuyến $\\vec{n} = (3; -2)$ có phương trình là:',
    options: [
      { key: 'A', text: '$3x - 2y + 1 = 0$' },
      { key: 'B', text: '$3x - 2y - 1 = 0$' },
      { key: 'C', text: '$2x + 3y - 8 = 0$' },
      { key: 'D', text: '$3x - 2y = 0$' },
    ],
    correctAnswer: 'A',
    solution: '$3(x - 1) - 2(y - 2) = 0 \\Leftrightarrow 3x - 2y + 1 = 0$.',
  },
  {
    id: 'q10_8',
    type: 'multiple_choice',
    level: 'ThongHieu',
    topicName: 'Phương trình đường tròn Oxy',
    content: 'Đường tròn $(C): (x - 2)^2 + (y + 3)^2 = 16$ có tâm $I$ và bán kính $R$ là:',
    options: [
      { key: 'A', text: '$I(2; -3), R = 4$' },
      { key: 'B', text: '$I(-2; 3), R = 4$' },
      { key: 'C', text: '$I(2; -3), R = 16$' },
      { key: 'D', text: '$I(-2; 3), R = 16$' },
    ],
    correctAnswer: 'A',
    solution: 'Tâm $I(2; -3)$, bán kính $R = \\sqrt{16} = 4$.',
  },
  {
    id: 'q10_9',
    type: 'multiple_choice',
    level: 'NhanBiet',
    topicName: 'Quy tắc cộng và quy tắc nhân',
    content: 'Một bạn có 5 chiếc áo sơ mi khác nhau và 4 chiếc quần tây khác nhau. Số cách chọn 1 bộ quần áo gồm 1 áo và 1 quần là:',
    options: [
      { key: 'A', text: '$20$' },
      { key: 'B', text: '$9$' },
      { key: 'C', text: '$1$' },
      { key: 'D', text: '$40$' },
    ],
    correctAnswer: 'A',
    solution: 'Theo quy tắc nhân: $5 \\times 4 = 20$ cách.',
  },
  {
    id: 'q10_10',
    type: 'multiple_choice',
    level: 'ThongHieu',
    topicName: 'Hoán vị, chỉnh hợp, tổ hợp',
    content: 'Số cách chọn ra 3 học sinh từ một nhóm gồm 10 học sinh để đi lao động là:',
    options: [
      { key: 'A', text: '$C_{10}^3 = 120$' },
      { key: 'B', text: '$A_{10}^3 = 720$' },
      { key: 'C', text: '$30$' },
      { key: 'D', text: '$10^3 = 1000$' },
    ],
    correctAnswer: 'A',
    solution: 'Chọn 3 người từ 10 người không phân biệt thứ tự là $C_{10}^3 = 120$.',
  },
  {
    id: 'q10_11',
    type: 'multiple_choice',
    level: 'VanDung',
    topicName: 'Bất phương trình bậc nhất hai ẩn',
    content: 'Điểm nào sau đây thuộc miền nghiệm của bất phương trình $2x + y - 4 > 0$?',
    options: [
      { key: 'A', text: '$(2; 1)$' },
      { key: 'B', text: '$(1; 1)$' },
      { key: 'C', text: '$(0; 0)$' },
      { key: 'D', text: '$(1; 2)$' },
    ],
    correctAnswer: 'A',
    solution: 'Thay $(2; 1)$: $2(2) + 1 - 4 = 1 > 0$ (thỏa mãn).',
  },
  {
    id: 'q10_12',
    type: 'multiple_choice',
    level: 'ThongHieu',
    topicName: 'Xác suất cổ điển lớp 10',
    content: 'Gieo một con súc sắc cân đối và đồng chất một lần. Xác suất để xuất hiện mặt có số chấm là số chẵn bằng:',
    options: [
      { key: 'A', text: '$\\frac{1}{2}$' },
      { key: 'B', text: '$\\frac{1}{3}$' },
      { key: 'C', text: '$\\frac{1}{6}$' },
      { key: 'D', text: '$\\frac{2}{3}$' },
    ],
    correctAnswer: 'A',
    solution: 'Mặt chẵn gồm {2, 4, 6} $\\Rightarrow P = 3/6 = 1/2$.',
  },

  // PHẦN II: 4 CÂU ĐÚNG / SAI
  {
    id: 'q10_13',
    type: 'true_false',
    level: 'ThongHieu',
    topicName: 'Tam thức bậc hai',
    content: 'Cho tam thức bậc hai $f(x) = x^2 - 4x + 3$. Xét tính đúng/sai của các mệnh đề sau:',
    statements: [
      { id: 'a', text: 'Phương trình $f(x) = 0$ có hai nghiệm là $x = 1$ và $x = 3$.', isCorrect: true },
      { id: 'b', text: '$f(x) < 0$ khi và chỉ khi $x \\in (1; 3)$.', isCorrect: true },
      { id: 'c', text: '$f(x) > 0$ khi và chỉ khi $x \\in (3; +\\infty)$.', isCorrect: false },
      { id: 'd', text: '$f(0) = 3 > 0$.', isCorrect: true },
    ],
    solution: 'a) Đúng. b) Trong khoảng hai nghiệm tam thức mang dấu âm nên đúng. c) Thiếu khoảng $(-\\infty; 1)$ nên Sai. d) $f(0) = 3$ đúng.',
  },
  {
    id: 'q10_14',
    type: 'true_false',
    level: 'ThongHieu',
    topicName: 'Đường tròn trong mặt phẳng Oxy',
    content: 'Trong mặt phẳng tọa độ $Oxy$, cho đường tròn $(C): x^2 + y^2 - 4x + 6y - 12 = 0$. Xét tính đúng/sai:',
    statements: [
      { id: 'a', text: 'Tọa độ tâm của đường tròn là $I(2; -3)$.', isCorrect: true },
      { id: 'b', text: 'Bán kính của đường tròn là $R = 5$.', isCorrect: true },
      { id: 'c', text: 'Điểm $O(0; 0)$ nằm phía trong đường tròn.', isCorrect: true },
      { id: 'd', text: 'Đường tròn đi qua điểm $A(2; 2)$.', isCorrect: true },
    ],
    solution: 'a) $a = 2, b = -3 \\Rightarrow I(2; -3)$ (Đúng). b) $R = \\sqrt{2^2 + (-3)^2 - (-12)} = 5$ (Đúng). c) $0^2 + 0^2 - 12 < 0 \\Rightarrow$ nằm trong (Đúng). d) Thay (2; 2): $4 + 4 - 8 + 12 - 12 = 0$ (Đúng).',
  },
  {
    id: 'q10_15',
    type: 'true_false',
    level: 'VanDung',
    topicName: 'Hệ thức lượng và vectơ',
    content: 'Cho tam giác $ABC$ có $A(1; 2), B(-2; 6), C(9; 8)$. Xét tính đúng/sai:',
    statements: [
      { id: 'a', text: 'Vectơ $\\vec{AB} = (-3; 4)$.', isCorrect: true },
      { id: 'b', text: 'Độ dài cạnh $AB = 5$.', isCorrect: true },
      { id: 'c', text: 'Vectơ $\\vec{AC} = (8; 6)$.', isCorrect: true },
      { id: 'd', text: 'Tam giác $ABC$ vuông tại $A$.', isCorrect: true },
    ],
    solution: 'a) $\\vec{AB} = (-3; 4)$ (Đúng). b) $AB = 5$ (Đúng). c) $\\vec{AC} = (8; 6)$ (Đúng). d) $\\vec{AB} \\cdot \\vec{AC} = -3(8) + 4(6) = 0 \\Rightarrow$ vuông tại $A$ (Đúng).',
  },
  {
    id: 'q10_16',
    type: 'true_false',
    level: 'VanDung',
    topicName: 'Đại số tổ hợp và nhị thức Newton',
    content: 'Khai triển nhị thức Newton $P(x) = (2x - 1)^4$. Xét tính đúng/sai:',
    statements: [
      { id: 'a', text: 'Số hạng đầu tiên trong khai triển là $16x^4$.', isCorrect: true },
      { id: 'b', text: 'Hệ số tự do của khai triển là $1$.', isCorrect: true },
      { id: 'c', text: 'Số lượng các số hạng trong khai triển là $4$.', isCorrect: false },
      { id: 'd', text: 'Tổng tất cả các hệ số trong khai triển bằng $1$.', isCorrect: true },
    ],
    solution: 'a) $2^4 x^4 = 16x^4$ (Đúng). b) $(-1)^4 = 1$ (Đúng). c) Khai triển bậc 4 có $4 + 1 = 5$ số hạng (Sai). d) Cho $x = 1 \\Rightarrow (2-1)^4 = 1$ (Đúng).',
  },

  // PHẦN III: 6 CÂU TRẢ LỜI NGẮN
  {
    id: 'q10_17',
    type: 'short_answer',
    level: 'ThongHieu',
    topicName: 'Tọa độ đỉnh parabol',
    content: 'Tìm giá trị nhỏ nhất của hàm số $y = x^2 - 6x + 10$ trên $\\mathbb{R}$:',
    correctAnswer: '1',
    solution: 'Đỉnh $x = 3 \\Rightarrow y_{min} = 3^2 - 6(3) + 10 = 1$.',
  },
  {
    id: 'q10_18',
    type: 'short_answer',
    level: 'ThongHieu',
    topicName: 'Khoảng cách từ điểm đến đường thẳng',
    content: 'Tính khoảng cách từ điểm $M(1; 2)$ đến đường thẳng $\\Delta: 3x + 4y - 1 = 0$:',
    correctAnswer: '2',
    solution: '$d = \\frac{|3(1) + 4(2) - 1|}{\\sqrt{3^2 + 4^2}} = \\frac{10}{5} = 2$.',
  },
  {
    id: 'q10_19',
    type: 'short_answer',
    level: 'VanDung',
    topicName: 'Bán kính đường tròn ngoại tiếp tam giác',
    content: 'Cho tam giác $ABC$ có $a = 6$ và góc $\\widehat{A} = 30^\\circ$. Bán kính $R$ của đường tròn ngoại tiếp tam giác $ABC$ bằng:',
    correctAnswer: '6',
    solution: '$R = \\frac{a}{2\\sin A} = \\frac{6}{2\\sin 30^\\circ} = 6$.',
  },
  {
    id: 'q10_20',
    type: 'short_answer',
    level: 'VanDung',
    topicName: 'Đại số tổ hợp',
    content: 'Có bao nhiêu cách xếp 5 bạn học sinh thành một hàng dọc?',
    correctAnswer: '120',
    solution: '$5! = 120$ cách.',
  },
  {
    id: 'q10_21',
    type: 'short_answer',
    level: 'VanDung',
    topicName: 'Số nghiệm nguyên của bất phương trình',
    content: 'Tìm số nghiệm nguyên của bất phương trình $x^2 - 5x + 6 \\le 0$:',
    correctAnswer: '2',
    solution: '$2 \\le x \\le 3 \\Rightarrow x \\in \\{2; 3\\}$, có 2 nghiệm nguyên.',
  },
  {
    id: 'q10_22',
    type: 'short_answer',
    level: 'VanDung',
    topicName: 'Xác suất chọn tổ chức',
    content: 'Một hộp có 3 quả cầu đỏ và 7 quả cầu xanh. Lấy ngẫu nhiên 2 quả cầu. Xác suất để lấy được 2 quả cầu cùng màu đỏ bằng bao nhiêu (kết quả ghi dưới dạng số thập phân làm tròn 2 chữ số sau dấu phẩy)?',
    correctAnswer: '0.07',
    solution: '$C_3^2 / C_{10}^2 = 3/45 \\approx 0.07$.',
  },
];

export const getMath10Test = (config: TestConfig): GeneratedTest => ({
  id: `test_10_${Date.now()}`,
  title: config.title || 'BÀI KIỂM TRA TOÁN 10 - GDPT 2018',
  config: { ...config, grade: '10' },
  questions: MATH_10_QUESTIONS,
  createdAt: new Date().toISOString(),
});
